name: pipeline

on: [push, pull_request]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Install miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: covid-test
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install --file requirements.txt
        conda install pytest pytest-cov
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --cov=./covid --cov-report term-missing covid/tests.py
    - name: Run dedicated coverage step
      if: matrix.python-version == 3.7
      shell: bash -l {0}
      run: |
        pytest --cov=./covid --cov-report xml --cov-report term-missing covid/tests.py
